### ISSUE TITLE
Create Combos?

### ISSUE THREAD

**Issue by Jacob1010-h** [Patribots4738/ChargedUp2023#101]
Should we create combos for the controller, and is it a good idea in general? I think not, but what is everyone's opinion on this?

The reason for not is that it could add complexity to the controller and driving in general. This added complexity could confuse the driver in a tense situation.

**Comment by PatribotsProgramming** [comment]
That is the worst idea my 2am brain has ever thought of

**Comment by PatribotsProgramming** [comment]
combos would make things quite difficult for any operator, especially if it is in an elim match 0-0
