### ISSUE TITLE
Set max angular velocity based on our arm X position

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#113]
use FK to slow down spin when extended but speed up when stowed

**Comment by PatribotsProgramming** [comment]
[desmos] (https://www.desmos.com/calculator/fqyyldertp) :>
Apply a deadband at 6.5, anything less than that is fully within the frame perimeter

**Comment by PatribotsProgramming** [comment]
arm X of ~30 inches should return something around 3 PI max angular speeds, and an arm X of ~0 inches (remember the deadband will return zero if anything under 6.5 is given) our max angular speed should be roughly 6-8-10PI (needs testing)

**Comment by PatribotsProgramming** [comment]
java "Lerp" should suffice
pseudocode:
`import java.util.Lerp;
maxAngularVelocity = Util.Lerp(MIN_ANGULAR_SPEED, MAX_ANGULAR_SPEED, Math.clamp(MathUtil.applyDeadband(arm.getXPosition(), 6.5)/30, 0, 1)`

**Comment by GalexY727** [comment]
60f9a4dabe00e0a46b24fd49ea7905734988b168
