### ISSUE TITLE
Lower the cube intake to be closer to the ground

### ISSUE THREAD

**Issue by PatribotsProgramming** [Patribots4738/ChargedUp2023#117]
Ideally, this will make it so that we are able to contact the cubes quicker and thus intake with more precision

**Comment by GalexY727** [comment]
After a full day of testing, I think that the better solution is to index the claw against our bumper to prevent swinging, as seen in our 3P autos

**Comment by GalexY727** [comment]
Meaning that this is ready to test :o

**Comment by GalexY727** [comment]
I am content with its current position, but we can easily tweak it in pits/practice fields at houston

**Comment by GalexY727** [comment]
gosh that was weird to type

**Comment by GalexY727** [comment]
gosh that was weird to type

**Comment by GalexY727** [comment]
h

o

u

s

t

o

n

**Comment by GalexY727** [comment]
More modifications were made today, after countless misses at houston I don't know how it never works at comps. It seemed okay enough today in testing so... marking this as complete until we go to chezy and realize it never worked in the first place...
