### ISSUE TITLE
Implement PS5 Controllers rather than Xbox

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#146]
With hopes that we have some future upgrades for our drivers...

**Comment by GalexY727** [comment]
It will be required to use [ds4controller ](https://ds4-windows.com/download/ryochan7-ds4windows/) which will need to be installed on the driver station. Other than that, [this cd](https://www.chiefdelphi.com/t/ps5-dualsense-controller/401506/5) post explains that it works just the same as the ps4 controller class. Rubmles must be handled through the Xbox controller class, unfortunately.

**Comment by GalexY727** [comment]
POV also works the same, so that makes [OICalc](https://github.com/Patribots4738/ChargedUp2023/blob/main/src/main/java/calc/OICalc.java) a lot easier to translate. We might not need to use [OICalc.toCircle()](https://www.desmos.com/calculator/e07raajzh5), though.

**Comment by GalexY727** [comment]
@Jacob1010-h Do you have time to do this or should I? We have a branch [here](https://github.com/Patribots4738/ChargedUp2023/tree/146-PS5-Controller) which is ready to work on.

**Comment by GalexY727** [comment]
Major progress with [964e07c](https://github.com/Patribots4738/ChargedUp2023/commit/964e07cdb640d9a4217ad574a4d990bb4f975e37)

**Comment by GalexY727** [comment]
using DS4 there are no changes needed in code

**Comment by Jacob1010-h** [comment]
> @Jacob1010-h Do you have time to do this or should I? We have a branch [here](https://github.com/Patribots4738/ChargedUp2023/tree/146-PS5-Controller) which is ready to work on.

Sorry for not responding right away, i was distracted with family stuff, thank you for getting this done

**Comment by GalexY727** [comment]
All good, don't worry about it
