### ISSUE TITLE
Ensure the robot does not wait to align to Charge Pad after auto

### ISSUE THREAD

**Issue by PatribotsProgramming** [Patribots4738/ChargedUp2023#37]
This can be done a couple of ways, the easiest may be to have the charge pad auto paths end quicker so the robot can jump straight to leveling

**Comment by GalexY727** [comment]
Yayyyyy, we just need to tune it using #53

**Comment by GalexY727** [comment]
This issue has appeared to come back after the IMU reported a roll of >90 during auto, but <5 during teleop.

**Comment by GalexY727** [comment]
No, no, maybe it should wait. We can tell the robot to end where we think the center is to speed up the auto alignment process

**Comment by Jacob1010-h** [comment]
Alex the issue closer!! GO GO GO

**Comment by GalexY727** [comment]
GO GO OGO GO

**Comment by Jacob1010-h** [comment]
Time to test!! 🙏

**Comment by Jacob1010-h** [comment]
@GalexY727

**Comment by GalexY727** [comment]
thank u thank u
