### ISSUE TITLE
Refactor modular autonomous to a Hashmap

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#38]
Change all of the modular auto paths to fit inside of one hashmap, with the key being the path name, and the value being the new Waypoint that gets created. This will reduce redundancy in the code so things only need to be made once, but can be cross-referenced throughout the code. This is very similar to how the paths currently are, this issue only aims to extend that capability to the waypoints, and not limit it by the trajectory.
Just incase it was miscommunicated, this is to be done in the modular-autonomous branch.

**Comment by GalexY727** [comment]
Great job Jacob, I hope to push this in before SDR

**Comment by GalexY727** [comment]
Thanks for getting this done so quickly Jacob... Unfortunately, we are required to sway away from the hashmap solution to create 9_D_8... but that's okay... 
I find it ironic that this is #38

**Comment by Jacob1010-h** [comment]
SDR be like 💀.

**Comment by GalexY727** [comment]
I swear I said I was gonna have this done by SDR... I HAVE A REASON I SWEAR

Since we recently transitioned into making a single path to tackle the movement of 9_D_8, for example, the hashmap solution wouldn't be able to know that we are looking for these weird paths and not just 9_D, and D_8. I would like to make it **very clear** that this is a great idea and that great teams such as Jack In the Bot use this kind of system to get their super cool things done. But, Since we have things such as 9_D_8_BLUE and 9_D_8_RED, 9_D, D_8, hashmap solution isn't so perfect anymore :(

This is the way it should have been done from the get-go, I'll be honest. Even to just make those legacy paths and to have other options like the newer variants, I do apologize for never getting around to finishing this merge. Thank you @Jacob1010-h for getting this written so quickly!

**Comment by GalexY727** [comment]
the label of death...
