### ISSUE TITLE
Fix claw losing grip

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#48]
The claw has been noted to lose grip on game elements since the arm moves so fast... 
Speed up the claw so that it doesn't pop the cubes but also keeps the cones in its handling.
We may want to see the return of the claw and cone speeds for the claw using coneMode.

**Comment by PatribotsProgramming** [comment]
It appears that this issue is caused mainly by the brown outs that we experience near the end of a match, but we can try to index the cone by smushing it against a bumper, or arm, or similar.

**Comment by GalexY727** [comment]
4e3b4b77bbc00d56ec023b364ba513c3af291e4b definitely should aid in this.
