### ISSUE TITLE
Allow for substation tag alignment

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#49]
... so the robot isn't smashing the claw into the wall
Find the middle ground between the human tag arm position's X value and the location of the arm on the chassis.

**Comment by GalexY727** [comment]
Update: human player just doesn't work at all anymore, kinda interesting...

**Comment by GalexY727** [comment]
@Jacob1010-h, would you mind looking through the code in case I missed something?

**Comment by GalexY727** [comment]
renamed from Move back the human player offset on the X

**Comment by GalexY727** [comment]
0130afa19c7b9b4fea528ad1d12187d759f018b4
AAAAAA UNITS CONVERTSIONG AAAAA

**Comment by Jacob1010-h** [comment]
Should this be tested? I thought we did this.
If we did: remove the help wanted and add "needs testing"

**Comment by PatribotsProgramming** [comment]
Allowed, but not too feasible, may be better to just manually take the game piece
