### ISSUE TITLE
Charge pad auto align

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#53]
Automatically align the robot to the charge pad by using a tilt calculation using all 3 axis of the IMU

**Comment by PatribotsProgramming** [comment]
Post-CVR was nice in that it had a 100% engage rate for the robot, although it looked really sketch.

**Comment by GalexY727** [comment]
The structure is all there, we just need to tune it on the real charge pad at the practice field at SDR (:

**Comment by GalexY727** [comment]
One weird thing to note is that we must compensate for auto/teleop since we may end closer to the center of the pad in auto, and thus would require a much smaller speed to get level

**Comment by GalexY727** [comment]
I smell a one-line if statement... @Jacob1010-h
