### ISSUE TITLE
More LEDs!

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#74]
add some to the back of the robot and maybe the arm if needed, so the human player always knows what we want or to tell us we are asking for the wrong object

**Comment by PatribotsProgramming** [comment]
Should be working now, I made the LEDs flash and brought the code from the LED testing repo here.
@RandomPro8

**Comment by GalexY727** [comment]
Well not they don't turn on :(

**Comment by RandomPro8** [comment]
Looks like I'll be testing in EDD then :(

**Comment by GalexY727** [comment]
All that needs to be done now is to fix the indexes on the belly pan, everything else is flawless
