### ISSUE TITLE
Clamp the odometery for the swerve so it is harder to overshoot

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#79]
if X < 2 (for example) and we are on blue alliance, set X = 2, and if Y is < 0, set it to 0; if Y > FIELD_HEIGHT_METERS, Y = FIELD_HEIGHT_METERS.

Note that the X value must only be clamped on the low end on blue alliance, and only clamped on the high end on red alliance.

**Comment by PatribotsProgramming** [comment]
Merged into #96

**Comment by PatribotsProgramming** [comment]
This resulted in some strange reaction to the robot as if resetting the odometry was taking a lot of time

**Comment by PatribotsProgramming** [comment]
@Jacob1010-h :(

**Comment by GalexY727** [comment]
1 am solutions: only update the odometery if the requested value is within the range
i.e
if (swerve.getPose() < LIMIT) {
  update odometery 😮 
}

**Comment by GalexY727** [comment]
@Jacob1010-h :)

**Comment by Jacob1010-h** [comment]
Needs Testing???

**Comment by GalexY727** [comment]
thanks jacob 😭

**Comment by GalexY727** [comment]
While this PR never really got closed, I believe 2903f19e26ce55b09dfec7f0c0d26ebca35133b2 resolved this in full.
