### ISSUE TITLE
Add the constant names for each index in our PlacementConstants...

### ISSUE THREAD

**Issue by PatribotsProgramming** [Patribots4738/ChargedUp2023#81]
At the bottom of the constants, there are constants for the indexes of the array for the "ARM_POSITIONS"... 
Add the English name for the index as defined at the top of PlacementConstants for each index for ease of understanding.

**Comment by PatribotsProgramming** [comment]
This will not need testing and therefore should be pushed directly into main... I think.

**Comment by GalexY727** [comment]
This does not need testing you goober
