### ISSUE TITLE
Split auto alignment into three segments, rotation, then X, then Y

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/ChargedUp2023#94]
This would simplify the robot trying to do more things at once which would reduce the possibility of slipping or overcomplicating the auto alignment process. Each segment should be very fast on its own.

It should also be seen that this method will force the robot to go to the AprilTag every time, which should help fix up any odometry slippage.

**Comment by PatribotsProgramming** [comment]
I don't think that this is a great idea, it would be better for the PID to be tuned so that the robot can handle both scenarios
